### ISSUE TITLE
Cannot configure DbFirst

### ISSUE THREAD

**Issue by davidda** [bubibubi/JetEntityFrameworkProvider#11]
I followed the steps in your walkthrough for configuring DbFirst.

The dll is registered in GAC:
![image](https://user-images.githubusercontent.com/4145824/29670083-e742457a-88e5-11e7-9f8a-5e36dada3867.png)

The file _C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Config\machine.config_ shows this:
```
    <system.data>
        <DbProviderFactories>
		<add name="Microsoft SQL Server Compact Data Provider 4.0" invariant="System.Data.SqlServerCe.4.0" description=".NET Framework Data Provider for Microsoft SQL Server Compact" type="System.Data.SqlServerCe.SqlCeProviderFactory, System.Data.SqlServerCe, Version=4.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91"/>
		<add name="JetEntityFrameworkProvider" invariant="JetEntityFrameworkProvider" description="JetEntityFrameworkProvider" type="JetEntityFrameworkProvider.JetProviderFactory, JetEntityFrameworkProvider, Version=1.2.10.0, Culture=neutral, PublicKeyToken=756cf6beb8fe7b41" />
	</DbProviderFactories>
    </system.data>
```

Then, I created a new project and added EF 6.1.3 via NuGet. Finally, I opened the new item dialog and chose "ADO.NET Entity Data Model" and then "Code First from Database".

However, the dialog does not show the entry:
![image](https://user-images.githubusercontent.com/4145824/29670024-aa56e350-88e5-11e7-8f6e-8c865149d3e0.png)

I've tried with VS 2015 (registry 14.0_Config) and VS 2012 (registry 12.0_Config) and even VS 2017. I've also tried on another computer with VS 2015. For the latter I've attached the registry items DataProviders and DataSources:
[HKEY_CURRENT_USER-SOFTWARE-Microsoft-VisualStudio-14.0_Config-DataProviders.reg.txt](https://github.com/bubibubi/JetEntityFrameworkProvider/files/1249100/HKEY_CURRENT_USER-SOFTWARE-Microsoft-VisualStudio-14.0_Config-DataProviders.reg.txt)
[HKEY_CURRENT_USER-SOFTWARE-Microsoft-VisualStudio-14.0_Config-DataSources.reg.txt](https://github.com/bubibubi/JetEntityFrameworkProvider/files/1249101/HKEY_CURRENT_USER-SOFTWARE-Microsoft-VisualStudio-14.0_Config-DataSources.reg.txt)

**Comment by bubibubi** [comment]
In your case is missing the DDEX provider. Probably something wrong with the registry.

**Comment by davidda** [comment]
I don't see anything wrong. The content of the reg files you posted is contained basically identical in the reg files I posted.
I'm on Windows 10, latest version. Not sure if that could make a difference.

**Comment by bubibubi** [comment]
Same OS here. Try compile everything using x86 (VS runs in x86).

**Comment by bubibubi** [comment]
I'm thinking about your issue.
Did you install the provider also from github?
To see of the provider is in the gac you can also try to check it writing some lines of code using dbproviderfactories. In this days I'll also do it.

**Comment by davidda** [comment]
Okay I figured it out. To make the provider show up in the list:
- The target project must be set to x86
- The target project must have the JetEntityFramework NuGet package installed and be compiled afterwards

It is not nessecary to compile the provider in x86.
