### ISSUE TITLE
NuGet package with AnyCPU processor architecture

### ISSUE THREAD

**Issue by erikvdv1** [bubibubi/JetEntityFrameworkProvider#12]
Right now the NuGet package is compiled as x86. When targeting my solution as AnyCPU I get the warning message below. Can you compile the NuGet package as AnyCPU, or does the JetProvider not support x64?

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1987,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Users\[User]\.nuget\packages\jetentityframeworkprovider\1.2.11\lib\JetEntityFrameworkProvider.dll", "x86".
This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
```

**Comment by bubibubi** [comment]
The problem is that often, compiling with AnyCPU or 64 bits, the OleDB provider for Microsoft Access does not work.
I think there is a way to install 32 and 64 bit OleDB provider but I need to test it.

**Comment by raytrask** [comment]
I use x86 target to get red of the warning and it has not been a problem for me so far.

**Comment by erikvdv1** [comment]
I use x86 as well to prevent the error, but I rather not have a library dictate the architecture of my whole application. If you compile as AnyCPU you can still run as 32-bit on a 64-but machine with the "Any CPU 32-bit preferred" option in your app.

Also the OleDB provider comes in a x64 flavor see the link below for available runtimes. https://stackoverflow.com/questions/6649363/microsoft-ace-oledb-12-0-provider-is-not-registered-on-the-local-machine/32247214#32247214

**Comment by seiyata** [comment]
Is 64 bit support is included in the latest release?

**Comment by bubibubi** [comment]
Yes. Check above comments for OleDB runtimes.
