### ISSUE TITLE
Issue with Graph Diff and Guids

### ISSUE THREAD

**Issue by bzuillsmith** [bubibubi/JetEntityFrameworkProvider#20]
I'm attempting to use GraphDiff with an MS Access DB and one of my entities uses a Guid. I get ```Primitive type kind Guid is not supported by the Jet Provider``` when running ```GraphDiff.UpdateGraph(...)``` on this particular entity.

The line it occurs on is here. I notice the Guid case goes to this exception.
 https://github.com/bubibubi/JetEntityFrameworkProvider/blob/8c6a21275667fd3e5619b8547137b9401a4088ef/JetEntityFrameworkProvider/GeneratorSql/SqlGenerator.cs#L981-L984 

Why isn't ```.ToString()``` just called on the Guid? I don't fully understand how GraphDiff does things to end up with the Guid as a constant expression. Is there a reason JetEntityFrameworkProvider doesn't allow that or is this just a bug?

**Comment by bubibubi** [comment]
You can find it also un nuget if you enable previews
6.1.3-beta3
