### ISSUE TITLE
Vb.net issue

### ISSUE THREAD

**Issue by ohuanasis** [bubibubi/JetEntityFrameworkProvider#3]
I have used this framework successfully with c#, however when attempting to replicate with vb.net. I'm unable. Is this framework only compatible with c#?

**Comment by bubibubi** [comment]
It should be compatible with every .Net Language.
You could have issues with 32/64 bits because of the OLEDB provider installed on your machine otherwise it should work with VB as well as C#.
If you send me a small sample of non working code I can have a look.

**Comment by ohuanasis** [comment]
yes it was related to the OLEDB provider. It is good. This framework is great.
