### ISSUE TITLE
Renaming a foreign key: Required attribute does not work anymore

### ISSUE THREAD

**Issue by PatriceDargenton** [bubibubi/JetEntityFrameworkProvider#40]
Using this code, we can choose explicitly the name of a foreign key:

public virtual Standard Standard { get; set; } // Standard_StandardId

[ForeignKey("StandardId")]
public virtual Standard Standard { get; set; }
public int StandardId { get; set; }

It works fine, but the Required attribute no longer works then. Any solution?

**Comment by bubibubi** [comment]
To understand what's happening you can enable SQL command trace.
The commands are traced to console.
The statement to enable the trace is JetConnection.ShowSqlStatements = true

**Comment by PatriceDargenton** [comment]
Ok, using SQL command trace, I found my mistake: in fact everything works fine, I confused something! Thank you!
