### ISSUE TITLE
How to set the description of a column?

### ISSUE THREAD

**Issue by PatriceDargenton** [bubibubi/JetEntityFrameworkProvider#41]
There is a solution here for Entity Framework:
https://stackoverflow.com/questions/38996810/in-ef-code-first-is-there-a-data-annotation-for-description-field

But the query (sp_addextendedproperty) is not valid for MS-Access. Any solution?

**Comment by bubibubi** [comment]
At low level, the only way to set description is to use ADOX (but I never tried it).
In JetEntityFrameworkProvider I never use ADOX (I use it in EF.Core but there are some limitations).
You can try to use ADOX but then your app probably will run only in 32 bit mode.

**Comment by PatriceDargenton** [comment]
OK, thank you for the information.
