### ISSUE TITLE
when MS Access is installed in 64 bit, JetEntityFramework not working (The 'Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine)

### ISSUE THREAD

**Issue by nnmmss** [bubibubi/JetEntityFrameworkProvider#64]
I have programmed an application with visual studio 2022 c# and MS Access db. So I used JetEntityFrameworkProvider Ver. 6.1.5rc3 for connecting. So this is the only situation which application works
1. Target Platform > Any CPU ,    prefer 32 bit : checked
2. Office installed in 32 bit

but I need it would work in Office 64 bit also, so I installed Microsoft Access Database Engine 2016 (64 bit) to connect to Office 64 but through the JetEntityFramework, but no success

so my question is : if I want to use JetEntityFramework , should I install office in 32 bit only? if no, how should I do that

**Comment by bubibubi** [comment]
You need to have 2 different Apps one 32 bit the other 64 bit (Any CPU without prefer 32 bit is ok).
The end user should start the proper App.
Other problem is running Microsoft Database Engine 32 bit and 64 bit on the same machine. Mirosoft says that's impossible.

I suggest to use only 64 bit (I'm doing so).

It does not solve your problem but you could check also Ef Core and EF Core provider. This is the github repo CirrusRedOrg/EntityFrameworkCore.Jet
