### ISSUE TITLE
The link does not work in readme.md

### ISSUE THREAD

**Issue by digentltd** [bubibubi/JetEntityFrameworkProvider#8]
The link in the readme.md in docs that is titled Enabling DB First links to https://github.com/bubibubi/JetEntityFrameworkProvider/blob/master/docs/Enabling_DB_First.md

should be
https://github.com/bubibubi/JetEntityFrameworkProvider/blob/master/docs/Enabling_db_first.md

**Comment by bubibubi** [comment]
Thanks
